// AUTO-GENERATED by scripts/gen_blur.py. Per-client LQIP maps.
// Server-imported; only the rendered client's map serializes into its page.

import b_flamengo from "@/content/clients/flamengo/blur.json";
import b_a1_auto from "@/content/clients/a1-auto/blur.json";
import b_university_city_barbershop from "@/content/clients/university-city-barbershop/blur.json";
import b_dekalb_mechanical from "@/content/clients/dekalb-mechanical/blur.json";
import b_china_house from "@/content/clients/china-house/blur.json";
import b_genoa_animal_hospital from "@/content/clients/genoa-animal-hospital/blur.json";
import b_realize_athletics from "@/content/clients/realize-athletics/blur.json";
import b_leza_nail_spa from "@/content/clients/leza-nail-spa/blur.json";
import b_friedrichs_eye from "@/content/clients/friedrichs-eye/blur.json";
import b_woodys_orchard from "@/content/clients/woodys-orchard/blur.json";
import b_todd_curtis_orthodontist from "@/content/clients/todd-curtis-orthodontist/blur.json";
import b_pizza_villa from "@/content/clients/pizza-villa/blur.json";
import b_the_montcler from "@/content/clients/the-montcler/blur.json";
import b_dearborn_cafe from "@/content/clients/dearborn-cafe/blur.json";
import b_lord_stanleys from "@/content/clients/lord-stanleys/blur.json";
import b_mvps_sports_bar from "@/content/clients/mvps-sports-bar/blur.json";
import b_lovells_tire from "@/content/clients/lovells-tire/blur.json";
import b_beas_wok from "@/content/clients/beas-wok/blur.json";
import b_wired_nutrition from "@/content/clients/wired-nutrition/blur.json";
import b_bowlrrito from "@/content/clients/bowlrrito/blur.json";
import b_my1_hair from "@/content/clients/my1-hair/blur.json";
import b_tails_humane from "@/content/clients/tails-humane/blur.json";
import b_johnny_ks from "@/content/clients/johnny-ks/blur.json";
import b_exquisite_skillet from "@/content/clients/exquisite-skillet/blur.json";
import b_chicago_beauty from "@/content/clients/chicago-beauty/blur.json";
import b_tastee_bite from "@/content/clients/tastee-bite/blur.json";
import b_fattys_pub from "@/content/clients/fattys-pub/blur.json";
import b_cortland_vet from "@/content/clients/cortland-vet/blur.json";
import b_inbodens_meats from "@/content/clients/inbodens-meats/blur.json";
import b_cast_iron_coffee from "@/content/clients/cast-iron-coffee/blur.json";
import b_paw_lickin_good from "@/content/clients/paw-lickin-good/blur.json";
import b_pilates_plus from "@/content/clients/pilates-plus/blur.json";
import b_mccoy_chiropractic from "@/content/clients/mccoy-chiropractic/blur.json";
import b_cronauer_law from "@/content/clients/cronauer-law/blur.json";
import b_pardridge_insurance from "@/content/clients/pardridge-insurance/blur.json";
import b_white_oak_tax from "@/content/clients/white-oak-tax/blur.json";
import b_south_moon_bbq from "@/content/clients/south-moon-bbq/blur.json";
import b_prairie_path_cycles from "@/content/clients/prairie-path-cycles/blur.json";
import b_kiss_the_sky from "@/content/clients/kiss-the-sky/blur.json";
import b_yellow_bird_books from "@/content/clients/yellow-bird-books/blur.json";
import b_mad_batter_bakery from "@/content/clients/mad-batter-bakery/blur.json";
import b_geneva_winery from "@/content/clients/geneva-winery/blur.json";
import b_celidan_florist from "@/content/clients/celidan-florist/blur.json";
import b_noon_whistle_brewing from "@/content/clients/noon-whistle-brewing/blur.json";
import b_suburban_music from "@/content/clients/suburban-music/blur.json";
import b_pottery_bayou from "@/content/clients/pottery-bayou/blur.json";
import b_flavor_spice from "@/content/clients/flavor-spice/blur.json";
import b_beidelman_furniture from "@/content/clients/beidelman-furniture/blur.json";
import b_kramer_photography from "@/content/clients/kramer-photography/blur.json";
import b_victory_mma from "@/content/clients/victory-mma/blur.json";
import b_schmaltz_deli from "@/content/clients/schmaltz-deli/blur.json";
import b_sapphire_tattoo from "@/content/clients/sapphire-tattoo/blur.json";
import b_envision_dance from "@/content/clients/envision-dance/blur.json";
import b_costello_jewelry from "@/content/clients/costello-jewelry/blur.json";
import b_all_chocolate_kitchen from "@/content/clients/all-chocolate-kitchen/blur.json";
import b_andersons_toyshop from "@/content/clients/andersons-toyshop/blur.json";
import b_arcada_theater from "@/content/clients/arcada-theater/blur.json";
import b_elite_boba from "@/content/clients/elite-boba/blur.json";
import b_nona_jos from "@/content/clients/nona-jos/blur.json";
import b_growing_place from "@/content/clients/growing-place/blur.json";
import b_naperville_running from "@/content/clients/naperville-running/blur.json";
import b_riddlebox_escape from "@/content/clients/riddlebox-escape/blur.json";
import b_astro_fun_world from "@/content/clients/astro-fun-world/blur.json";
import b_lindsays_cobbler from "@/content/clients/lindsays-cobbler/blur.json";
import b_lisle_lanes from "@/content/clients/lisle-lanes/blur.json";
import b_pub_west from "@/content/clients/pub-west/blur.json";
import b_the_flame from "@/content/clients/the-flame/blur.json";
import b_tapa_la_luna from "@/content/clients/tapa-la-luna/blur.json";
import b_anderson_auto_body from "@/content/clients/anderson-auto-body/blur.json";
import b_la_michoacana from "@/content/clients/la-michoacana/blur.json";
import b_hinks_bar_and_grill from "@/content/clients/hinks-bar-and-grill/blur.json";
import b_star_34_cafe from "@/content/clients/star-34-cafe/blur.json";
import b_delts_electric from "@/content/clients/delts-electric/blur.json";
import b_votaw_plumbing from "@/content/clients/votaw-plumbing/blur.json";

const BLUR_BY_SLUG: Record<string, Record<string, string>> = {
  "flamengo": b_flamengo,
  "a1-auto": b_a1_auto,
  "university-city-barbershop": b_university_city_barbershop,
  "dekalb-mechanical": b_dekalb_mechanical,
  "china-house": b_china_house,
  "genoa-animal-hospital": b_genoa_animal_hospital,
  "realize-athletics": b_realize_athletics,
  "leza-nail-spa": b_leza_nail_spa,
  "friedrichs-eye": b_friedrichs_eye,
  "woodys-orchard": b_woodys_orchard,
  "todd-curtis-orthodontist": b_todd_curtis_orthodontist,
  "pizza-villa": b_pizza_villa,
  "the-montcler": b_the_montcler,
  "dearborn-cafe": b_dearborn_cafe,
  "lord-stanleys": b_lord_stanleys,
  "mvps-sports-bar": b_mvps_sports_bar,
  "lovells-tire": b_lovells_tire,
  "beas-wok": b_beas_wok,
  "wired-nutrition": b_wired_nutrition,
  "bowlrrito": b_bowlrrito,
  "my1-hair": b_my1_hair,
  "tails-humane": b_tails_humane,
  "johnny-ks": b_johnny_ks,
  "exquisite-skillet": b_exquisite_skillet,
  "chicago-beauty": b_chicago_beauty,
  "tastee-bite": b_tastee_bite,
  "fattys-pub": b_fattys_pub,
  "cortland-vet": b_cortland_vet,
  "inbodens-meats": b_inbodens_meats,
  "cast-iron-coffee": b_cast_iron_coffee,
  "paw-lickin-good": b_paw_lickin_good,
  "pilates-plus": b_pilates_plus,
  "mccoy-chiropractic": b_mccoy_chiropractic,
  "cronauer-law": b_cronauer_law,
  "pardridge-insurance": b_pardridge_insurance,
  "white-oak-tax": b_white_oak_tax,
  "south-moon-bbq": b_south_moon_bbq,
  "prairie-path-cycles": b_prairie_path_cycles,
  "kiss-the-sky": b_kiss_the_sky,
  "yellow-bird-books": b_yellow_bird_books,
  "mad-batter-bakery": b_mad_batter_bakery,
  "geneva-winery": b_geneva_winery,
  "celidan-florist": b_celidan_florist,
  "noon-whistle-brewing": b_noon_whistle_brewing,
  "suburban-music": b_suburban_music,
  "pottery-bayou": b_pottery_bayou,
  "flavor-spice": b_flavor_spice,
  "beidelman-furniture": b_beidelman_furniture,
  "kramer-photography": b_kramer_photography,
  "victory-mma": b_victory_mma,
  "schmaltz-deli": b_schmaltz_deli,
  "sapphire-tattoo": b_sapphire_tattoo,
  "envision-dance": b_envision_dance,
  "costello-jewelry": b_costello_jewelry,
  "all-chocolate-kitchen": b_all_chocolate_kitchen,
  "andersons-toyshop": b_andersons_toyshop,
  "arcada-theater": b_arcada_theater,
  "elite-boba": b_elite_boba,
  "nona-jos": b_nona_jos,
  "growing-place": b_growing_place,
  "naperville-running": b_naperville_running,
  "riddlebox-escape": b_riddlebox_escape,
  "astro-fun-world": b_astro_fun_world,
  "lindsays-cobbler": b_lindsays_cobbler,
  "lisle-lanes": b_lisle_lanes,
  "pub-west": b_pub_west,
  "the-flame": b_the_flame,
  "tapa-la-luna": b_tapa_la_luna,
  "anderson-auto-body": b_anderson_auto_body,
  "la-michoacana": b_la_michoacana,
  "hinks-bar-and-grill": b_hinks_bar_and_grill,
  "star-34-cafe": b_star_34_cafe,
  "delts-electric": b_delts_electric,
  "votaw-plumbing": b_votaw_plumbing,
};

export function getBlur(slug: string): Record<string, string> {
  return BLUR_BY_SLUG[slug] ?? {};
}
