import copyJson from "@/content/copy.json";

/**
 * Typed access to the bilingual marketing copy generated by the
 * Copy & Localization agent. The `en` and `es` objects are structurally
 * identical, so a single `LangContent` type covers both.
 */

export type Lang = "en" | "es";

export interface Business {
  name: string;
  shortName: string;
  vertical: string;
  phone: string;
  phoneHref: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  mapsQuery: string;
  /** Real OSM coordinates (from data/targets.json) — used for JSON-LD geo. */
  lat?: number;
  lon?: number;
  /** Real OSM cuisine tag (restaurants) — used for JSON-LD servesCuisine. */
  cuisine?: string;
}

export interface MenuItem {
  name: string;
  desc: string;
  price: string;
  tags?: string[];
}

export interface MenuCategory {
  id: string;
  name: string;
  blurb: string;
  items: MenuItem[];
}

export interface Highlight {
  icon: string;
  title: string;
  text: string;
}

export interface LangContent {
  meta: { title: string; description: string };
  nav: { home: string; menu: string; about: string; gallery: string; visit: string; order: string };
  hero: {
    eyebrow: string; title: string; titleAccent: string; subtitle: string;
    ctaPrimary: string; ctaSecondary: string; badge: string;
  };
  highlights: Highlight[];
  menu: { heading: string; subheading: string; categories: MenuCategory[] };
  about: { heading: string; lead: string; paragraphs: string[]; stats: { value: string; label: string }[] };
  gallery: { heading: string; subheading: string; captions: string[] };
  testimonials: { heading: string; items: { quote: string; name: string; role: string }[] };
  visit: {
    heading: string; addressLabel: string; hoursLabel: string;
    hours: { day: string; time: string }[]; phoneLabel: string; directions: string;
    /** Researched, verifiable locale context ("Two blocks east of the
     *  Egyptian Theatre on Lincoln Highway") — facts only, no puffery. */
    neighborhood?: string;
  };
  cta: { heading: string; text: string; button: string };
  /** Authority/wellness archetype "how it works" flow (optional). */
  process?: { heading: string; steps: { title: string; text: string }[] };
  /** Wellness archetype guided-visit flow (optional). */
  ritual?: { heading: string; steps: { title: string; text: string }[] };
  /** Authority archetype FAQ accordion (optional). */
  faq?: { heading: string; items: { q: string; a: string }[] };
  form: {
    heading: string; subheading: string; name: string; email: string; phone: string;
    partySize: string; date: string; message: string; submit: string; sending: string;
    success: string; error: string; consent: string;
  };
  footer: {
    tagline: string;
    rights: string;
    quickLinks: string;
    hoursTitle: string;
    demoNote?: string;
    allSites?: string;
  };
}

export interface SiteContent {
  business: Business;
  en: LangContent;
  es: LangContent;
}

/** The flagship (Flamengo) site, used by the home route. */
export const flamengo = copyJson as unknown as SiteContent;

/** Default decorative emoji set (Flamengo / food). Clients can override. */
export const DEFAULT_EMOJIS = ["🌮", "🍦", "🌶️", "🥑", "🍋", "🥘"];

export const LANGS: { code: Lang; label: string }[] = [
  { code: "en", label: "EN" },
  { code: "es", label: "ES" },
];
